export const REALTIME_RULES = {
  HISTORY_SOURCE: "API",
  REALTIME_SOURCE: "WEBSOCKET",
  OFFLINE_RECOVERY: "PULL_ON_RECONNECT",
  PRESENCE_SCOPE: "GLOBAL",
  READ_RECEIPT_RULE: "READ_ALWAYS_WINS",
  EMPTY_CHATS_ALLOWED: false
} as const;
