export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT = "CONFLICT",
  RATE_LIMITED = "RATE_LIMITED",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  USER_NOT_FOUND = "USER_NOT_FOUND",
  USERNAME_TAKEN = "USERNAME_TAKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  CHAT_NOT_FOUND = "CHAT_NOT_FOUND",
  DIRECT_CHAT_ALREADY_EXISTS = "DIRECT_CHAT_ALREADY_EXISTS",

  MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND",
  INVALID_MESSAGE_STATE = "INVALID_MESSAGE_STATE",

  DEVICE_LIMIT_REACHED = "DEVICE_LIMIT_REACHED",
  SESSION_REVOKED = "SESSION_REVOKED",

  WS_INVALID_EVENT = "WS_INVALID_EVENT",
  WS_AUTH_REQUIRED = "WS_AUTH_REQUIRED"
}
